### ISSUE TITLE
Bash script doesn't work on macOS

### ISSUE THREAD

**Issue by tkadur** [jluningp/smlformat#2]
It looks like the `readlink` that ships with macOS doesn't support `-f`.

```
$ ./smlformat -i ../test.sml
readlink: illegal option -- f
usage: readlink [-n] [file ...]
```

Tested on macOS 10.15.4

**Comment by jluningp** [comment]
If you replace the top line of the file with 
```
BASE_DIR=$(dirname "$0")
```
it should work. I also just pushed a fix, so if you pull and run it again, it should work.
